### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by leonluleonlu** [leonluleonlu/TheGlowingTree#1]
- [x] Project setup
- [x] Basic navigation
- [ ] Fix home page responsiveness
- [ ] Add links to footer
- [ ] Homepage contents
- [ ] Customise look
- [ ] Redesign logo
- [ ] Navigation from home
- [ ] Contact system
- [ ] Story page
- [ ] Status Quo page
- [ ] Solution page
- [ ] Sectional side navigation
